Metadata:
  License: Apache-2.0
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  AvailabilityZone:
    Description: "Select Availability Zone for instances"
    Type: AWS::EC2::AvailabilityZone::Name
  AllowSSHCidrBlock:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 201.81.78.137/32
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  MinSize:
    Description: "Minimum size of instances for AutoScaling Group"
    Type: Number
  MaxSize:
    Description: "Maximum size of instances for AutoScaling Group"
    Type: Number
  KeyPair:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: AWS::EC2::KeyPair::KeyName
    Default: aws-fis-target-instance-keypair
    ConstraintDescription: must be the name of an existing EC2 KeyPair.

Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "AWS FIS Target Instances Security Group" # Required
      GroupName: "aws-fis-target-instances-sg"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: !Ref AllowSSHCidrBlock
      Tags:
        - Key: "Name"
          Value: "AWS FIS Target SG"
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: "lcnft-aws-fis-target-instances"
      LaunchTemplateData:
        Placement:
          Tenancy: default
        ImageId: "ami-09d3b3274b6c5d4aa"
        KeyName: !Ref KeyPair
        InstanceType: "t2.micro"
        UserData:
          Fn::Base64: |
            #!/bin/bash
            # update
            sudo yum -y update
            sudo yum -y upgrade

            # enable EPEL6 by changing enabled=0 -> enabled=1
            sudo vim /etc/yum.repos.d/epel.repo

            # install htop
            sudo yum install htop
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: "asg-aws-fis-target-instances"
      AvailabilityZones:
        - !Ref AvailabilityZone
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: 1
      DesiredCapacity: !Ref MinSize
      MaxSize: !Ref MaxSize # Required
      MinSize: !Ref MinSize # Required
      TerminationPolicies:
        - Default
  ASGScalingPolicyHigh:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      PolicyType: StepScaling
      AdjustmentType: ChangeInCapacity
      StepAdjustments: 
        - MetricIntervalLowerBound: 0
          ScalingAdjustment: 1
  CPUAlarmHigh:
    Type: AWS::CloudWatch::Alarm
    Properties:
      EvaluationPeriods: 2
      Statistic: Average
      Threshold: 90
      AlarmDescription: 'Scale out if CPU > 90% for 2 minutes'
      Period: 60
      AlarmActions:
      - !Ref ASGScalingPolicyHigh
      Namespace: AWS/EC2
      Dimensions:
      - Name: AutoScalingGroupName
        Value:
          !Ref AutoScalingGroup
      ComparisonOperator: GreaterThanThreshold
      MetricName: CPUUtilization
Outputs:
  SecurityGroup:
    Description: Security Group for AWS FIS Target Instances
    Value: !Ref SecurityGroup
  AutoScalingGroup:
    Description: AutoScaling Group for AWS FIS Target Instances
    Value: !Ref AutoScalingGroup
